// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manifest.get').default>>>>
    }
    '/api/post/:key': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/post/[key].get').default>>>>
    }
    '/api/posts.list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts.list.get').default>>>>
    }
    '/api/r2/get.:key': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2/get.[key]').default>>>>
    }
    '/api/r2/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2/list.get').default>>>>
    }
    '/api/r2/sign': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2/sign.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.8_@babel+plugin-syntax-typescript@7.29.7_@babel+core@7.29.7__db0_c52ffcced1213f23d76a2dbcdefc84d3/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}