allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  simple-git-hooks: set this to true or false
  vue-demi: set this to true or false
  weak: set this to true or false
