// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/21/2026, 12:19:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/root/r2-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/plugins/**/*.{js,ts,mjs}","/root/r2-blog/composables/**/*.{js,ts,mjs}","/root/r2-blog/utils/**/*.{js,ts,mjs}","/root/r2-blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/root/r2-blog/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;