name: update README
on:
  schedule:
    - cron: '0 0/2 * * * '  
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: devmount/profile-readme-stats@v1.3
      with:
        token: ${{ secrets.PROFILE_STATS_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot] 
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com 
        git add .
        git commit -m "📈 update profile stats"
        git push
        fi
