name: update README with profile stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: 🚀 posts
        run: node main.js
        env:
          POST_URL: ${{secrets.POST_URL}}
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: songdaochuanshu
          svg_out_path: github-contribution-grid-snake.svg
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1.2
        with:
          token: ${{ secrets.PROFILE_STATS_TOKEN }}
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "📈 update profile stats"
          git push
          fi