name: update README with profile stats
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: 🚀 posts
        run: node main.js
        env:
          POST_URL: ${{secrets.POST_URL}}
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: songdaochuanshu
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Generate README.md
        uses: devmount/profile-readme-stats@v1.3
        with:
          token: ${{ secrets.PROFILE_STATS_TOKEN }}
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "📈 update profile stats"
          git push
          fi

      # - uses: crazy-max/ghaction-github-pages@v2.1.3
      #   with:
      #     target_branch: output
      #     build_dir: dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PROFILE_STATS_TOKEN }}
