name: Trigger Fix Front Matter Script and Remove Duplicates

on:
  workflow_dispatch:

jobs:
  fix-and-remove-duplicates:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有权限写入仓库内容

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保所有历史记录都被克隆

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install  # 使用 npm 安装依赖项

    - name: Debug current directory and list files in content
      run: |
        pwd
        ls -la ./content

    - name: Run scripts if content/blog directory exists
      run: |
        if [ ! -d "./content/blog" ]; then
          echo "Directory ./content/blog does not exist."
          exit 1
        else
          node scripts/fix-front-matter.cjs
          node scripts/remove-duplicates.cjs
        fi

    - name: Check for changes
      id: check-changes
      run: |
        git config --global --add safe.directory /github/workspace
        CHANGED_FILES=$(git diff --name-only)
        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes detected."
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected:"
          echo "$CHANGED_FILES"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git user
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Stage and commit changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git add .
        git commit -m "chore: Update front matter and remove duplicates via GitHub Actions"

    - name: Push changes to remote
      if: steps.check-changes.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD